# Generated by Django 5.2.4 on 2025-08-01 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carouselimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers shown first)'),
        ),
    ]
