# Generated by Django 5.2.4 on 2026-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_carouselimage_options_carouselimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
