# Generated by Django 5.2.4 on 2026-05-17 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deduplicate_reviews(apps, schema_editor):
    """Keep only the most recent review per (product, user) pair."""
    Review = apps.get_model('store', 'Review')
    from django.db.models import Count, Max

    duplicates = (
        Review.objects.values('product_id', 'user_id')
        .annotate(cnt=Count('id'), max_id=Max('id'))
        .filter(cnt__gt=1)
    )
    for dup in duplicates:
        # Delete all but the most recent (highest id)
        Review.objects.filter(
            product_id=dup['product_id'],
            user_id=dup['user_id'],
        ).exclude(id=dup['max_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_carouselimage_link_carouselimage_subtitle_and_more'),
    ]

    operations = [
        # Step 1: Deduplicate reviews before adding constraint
        migrations.RunPython(deduplicate_reviews, migrations.RunPython.noop),
        # Step 2: Add unique_together on Review
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user')},
        ),
        # Step 3: Change Wishlist.user from ForeignKey to OneToOneField
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
